name: Workflow1
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Zagolovok
        run: echo "Text"
      - name: Many commands
        run: |
          node -v
          npm -v
